version: '3.4'

services:
  shopping.api:
    container_name: shoppingapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://shoppingdb:27017"
      - "DatabaseSettings:DatabaseName=CatalogDb"
      - "DatabaseSettings:CollectionName=products"
    ports:
      - "4000:80"
    depends_on:
    - shopping.db

  shopping.client:
    container_name: shoppingclient
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ShoppingUrl=http://shoppingapi"
    ports:
      - "5000:80"
    depends_on:   
    - shopping.api

  shopping.db:
    container_name: shoppingdb
    restart: always
    ports:
    - "27017:27017"


