apiVersion: v1
kind: Service
metadata:
  name: shoppingclient-service
spec:
  type: NodePort
  selector:
    app: shoppingclient
  ports:
  - protocol: TCP
    port: 5600
    targetPort: 80
    nodePort: 32234

